import {
    create, NAlert, NAutoComplete, NAvatar, NBackTop, NBadge, NBreadcrumb,
    NBreadcrumbItem, NButton, NCard, NCheckbox, NCheckboxGroup, NCol, NConfigProvider, NDataTable, NDatePicker, NDescriptions,
    NDescriptionsItem, NDialogProvider, NDivider, NDrawer,
    NDrawerContent, NDropdown, NElement, NEllipsis, NForm,
    NFormItem, NGradientText, NGrid,
    NGridItem, NH1,
    NH3,
    NH4, NIcon, NImage, NInput, NInputGroup, NInputNumber, NLayout, NLayoutContent,
    NLayoutFooter, NLayoutHeader, NLayoutSider, NList,
    NListItem, NLoadingBarProvider, NMenu, NMessageProvider, NModal, NNotificationProvider, NPagination, NPopover, NProgress, NRadio, NRadioGroup, NResult, NRow, NSelect, NSkeleton, NSpace, NSpin, NStep, NSteps, NSwitch, NTable, NTabPane, NTabs, NTag, NText, NThing, NTime, NTimePicker, NTooltip, NTree, NUpload
} from 'naive-ui';
import type { App } from 'vue';

const naive = create({
    components: [
        NMessageProvider,
        NDialogProvider,
        NConfigProvider,
        NInput,
        NButton,
        NForm,
        NFormItem,
        NCheckboxGroup,
        NCheckbox,
        NIcon,
        NLayout,
        NLayoutHeader,
        NLayoutContent,
        NLayoutFooter,
        NLayoutSider,
        NMenu,
        NBreadcrumb,
        NBreadcrumbItem,
        NDropdown,
        NSpace,
        NTooltip,
        NAvatar,
        NTabs,
        NTabPane,
        NCard,
        NRow,
        NCol,
        NDrawer,
        NDrawerContent,
        NDivider,
        NSwitch,
        NBadge,
        NAlert,
        NElement,
        NTag,
        NNotificationProvider,
        NProgress,
        NDatePicker,
        NGrid,
        NGridItem,
        NList,
        NListItem,
        NThing,
        NDataTable,
        NPopover,
        NPagination,
        NSelect,
        NRadioGroup,
        NRadio,
        NSteps,
        NStep,
        NInputGroup,
        NResult,
        NDescriptions,
        NDescriptionsItem,
        NTable,
        NInputNumber,
        NLoadingBarProvider,
        NModal,
        NUpload,
        NTree,
        NSpin,
        NTimePicker,
        NBackTop,
        NSkeleton,
        NEllipsis,
        NText,
        NH1,
        NH3,
        NH4,
        NAutoComplete,
        NTime,
        NImage,
        NGradientText,
    ],
});

export function setupNaive(app: App<Element>) {
    app.use(naive);
}
